### PR TITLE
Web API 2 and RouteAttribute handling in DefaultRouteDispatcher

### PR DESCRIPTION
**Pull request by MatthewRichards**
Further to PR https://github.com/ploeh/Hyprlinkr/pull/35 and issue https://github.com/ploeh/Hyprlinkr/issues/30, this PR covers:

* Upgrade to Web API 2.2
* Upgrade to .NET 4.5 (required by Web API 2)
* Update Hyprlinkr version number to 2.0
* Respecting [Route] attribute (the original issue)

Sorry, this breaks the rule about putting one thing in each PR... But the individual commits are reasonably granular so I can pull out into separate chunks if necessary.

A lot of diff for not very much change - the notable "real code changes" are:

* Modifying DefaultRouteDispatcher
* Merging UnitTest45 into UnitTest, and deleting the former (no need for a separate .NET 4.5 test project now that the main one is 4.5)
* Update ExampleProject to use a [Route] attribute
* Documentation changes

Feedback welcomed! (No rush - I've been ages getting round to this)

### CODE REVIEW

**Comment by andresmoschini** [comment]
Hi @MatthewRichards, I was trying to add it in a _ASP.NET 5 Preview Web API_ project, without success. 

Do you have any idea about how to do it?

**Comment by MatthewRichards** [comment]
Hi @andresmoschini, are you referring to this pull request in particular or Hyprlinkr in general? I haven’t looked into running either against ASP.NET 5 – I would imagine that this new v2 build of Hyprlinkr would stand very slightly more chance of working since it’s built against Web API 2 rather than 1, but I haven’t investigated how compatible Web API 2 and ASP.NET 5 are.

**Comment by andresmoschini** [comment]
Thanks for your response @MatthewRichards, I was referring to this particular PR. But, maybe Hyprlinkr is not necessary in MVC 6.

**Comment by ploeh** [comment]
Thank you for your contribution! It's now live as [Hyprlinkr 2.0.0](http://www.nuget.org/packages/Hyprlinkr/2.0.0).

**Comment by MatthewRichards** [comment]
Great, thanks!

**Comment by ploeh** [comment]
@MatthewRichards Do you have a Twitter profile?

I usually tweet out whenever there's a new major or minor version of any of the open source projects I take care of, and give credits to contributors if they want it.

**Comment by MatthewRichards** [comment]
My (fairly quiet!) Twitter profile is: RichardsMatthew (https://twitter.com/RichardsMatthew).

**Comment by ploeh** [comment]
Not quiet for long now, I think :smile:

**Pull request merged**
